import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "screen-256color"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
vi_mode_style = "Underline"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 13.5

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "M"
mods = "Control|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 1000

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6

